title: Zahra
description: Machine Learning Researcher
theme: jekyll-theme-minimal

# Navigation (optional)
header_pages:
  - index.md
  - about.md
  - resume.md
  - projects.md
  - blog.md
  - beyond.md
  - contact.md
