title: Zahra Golpayegani
description: Machine Learning Researcher
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - about.md
  - resume.md
  - projects.md
  - blog.md
  - beyond.md
  - contact.md
