title: Zahra Golpayegani
email: g&#46;golpa75&#64;gmail&#46;com
description: >- # this means to ignore newlines until next YAML item
  Researcher at Huawei
  Based in Toronto, Canada
baseurl: "" # leave empty unless hosted in a subfolder
url: "https://zahragolpa.github.io"

plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic


navigation:
  - name: Home
    link: ./index
  - name: Resume
    link: ./resume
  - name: Beyond Work
    link: ./beyond
    # sublist:
    #   - name: Image
    #     link: ./index.html#small-image
  # - name: Projects
  #   link: ./projects
